### ISSUE TITLE
 Map won't show up

### ISSUE THREAD

**Issue by stsdc** [trekawek/air-quality-info#100]
I'm trying to set up local environment and bumped into an issue with maps. I successfully obtained API key and enabled JS Maps API. Despite that, global map is not showing up:

![asasaassa](https://user-images.githubusercontent.com/6031763/209972116-f3c9ecf2-339c-45d0-a178-c5d1a1fedd45.png)

I can confirm that Maps API works by entering device configuration page and setting up device localization.
![image](https://user-images.githubusercontent.com/6031763/209970172-84af9dff-ef84-430d-930f-187d01194a03.png)

I did not touch anything in `config.php`, except `google_maps_key`. Did I miss something in configuration?

**Comment by trekawek** [comment]
I think this map will only show up if there are some active devices registered in the system. You may use pull-mode sensor.community devices to constantly generate test data. Also, please notice that there's a cache in place, so it may take up to 5 minutes for the map to catch-up with the pulled data.
