### ISSUE TITLE
Disabling graphs doesn't disable estimation lines

### ISSUE THREAD

**Issue by stsdc** [trekawek/air-quality-info#105]
In an event of data absence in serie a straight line is drawn. This line do not disappear when graph display is turned off.

It is expected that all graphical representation elements on chart will be turned off when respective toggle is clicked.
![obraz](https://user-images.githubusercontent.com/6031763/214034161-560f7c91-c2e1-4f18-8f59-ad24b7ed9c0c.png)

**Comment by trekawek** [comment]
Fixed. Thanks for the report.
