### ISSUE TITLE
Shows multiple values instead of one

### ISSUE THREAD

**Issue by stsdc** [trekawek/air-quality-info#106]
Shows additional values on  tooltip for 80% of 0X axis.

![image](https://user-images.githubusercontent.com/6031763/222438974-73fb2fc4-2a97-47c4-866f-c2577ade391c.png)

![image](https://user-images.githubusercontent.com/6031763/222439124-5b00ac3d-7252-4416-88f3-aa91c7f2184d.png)
![image](https://user-images.githubusercontent.com/6031763/222439523-7aacc28b-54d6-40df-8d87-76269de2f77f.png)

**Comment by trekawek** [comment]
Should be fixed now. Thanks!
