### ISSUE TITLE
HTTP/1.1 429 Too Many Requests when tying to push to https://api.aqi.eco/update/

### ISSUE THREAD

**Issue by DaleBCooper** [trekawek/air-quality-info#112]
Related to the hosted API endpoint, not the software itself, but I hope it is okay to report it here.

Since ~ 08:50 today my devices were not able to push the sensor data.
I use the default nettigo settings so the update interval is ~ 2 1/2 minutes.

Is api.aqi.eco undergoing a DoS attack so you had to set lower limits?

**Comment by DaleBCooper** [comment]
Working normally again since about 6 pm.

**Comment by trekawek** [comment]
Thanks for the report, there was a certificate update and apparently the new certificates are not compatible with the sensor firmware. The certificate was rolled back, in the meantime we're working on the firmware update.
