### ISSUE TITLE
Fatal error: Cannot declare class Locale, because the name is already in use in /home/users/xxxx/public_html/xxxx/lib/locale.php on line 2

### ISSUE THREAD

**Issue by lollul** [trekawek/air-quality-info#12]
Hello,
After recent changes I'm getting an error:
Fatal error: Cannot declare class Locale, because the name is already in use in /home/users/xxxx/public_html/xxxx/lib/locale.php on line 2
My provider is using PHP 7.2 and mysql.
Thank you for looking into it!

**Comment by lollul** [comment]
Sorry, I'm not a web developer and I have no idea how to fix it properly... But I've renamed the Locale class in locale.php and then removed the use of Locale in head.php and the site is working again (without the possibility to change locale obviously). Thought it might be useful.

**Comment by lollul** [comment]
...actually just renaming the Locale class and then using this renamed name in partials/head.php is enough to make locale work. Guess it is a bug in my PHP release.

**Comment by trekawek** [comment]
Thanks for the report. This should be fixed in 67ebf10f852781681aef51c4224186ed8ceae629.
