### ISSUE TITLE
annual stats failure

### ISSUE THREAD

**Issue by lollul** [trekawek/air-quality-info#13]
My database contains some gaps in PM sensor measurements when I was having trouble with the sensor. As a result the aggregate SQL from function getDailyAverages returns some NULLs and then the annual stats graph would fail to open.
I've applied the following patch to make it work:
```
--- htdocs/controllers/annual_stats_controller.php      2019-02-16 15:23:51.066059969 +0100
+++ /var/www/air-quality-info/controllers/annual_stats_controller.php   2019-02-18 08:34:58.678985112 +0100
@@ -24,8 +24,8 @@
         foreach ($averages as $day) {
             $pm10_level = find_level(PM10_THRESHOLDS_24H, $day['pm10_avg']);
             $pm25_level = find_level(PM25_THRESHOLDS_24H, $day['pm25_avg']);
-            $pm10_days_by_levels[$pm10_level]++;
-            $pm25_days_by_levels[$pm25_level]++;
+            if (isset($pm10_level)) { $pm10_days_by_levels[$pm10_level]++; }
+            if (isset($pm25_level)) { $pm25_days_by_levels[$pm25_level]++; }
         }
 
         $data = array();
```
I'm sure you'll find a better way to handle it. Thanks for looking into it!

**Comment by trekawek** [comment]
Thanks @lollul! Your patch proposal looks good. I modified it a bit - now there's an if checking if the daily average for given day is not null. I hope it'll work OK, even with the gaps.
