### ISSUE TITLE
DHT22 sensor data mapping

### ISSUE THREAD

**Issue by skornpion** [trekawek/air-quality-info#26]
The temperature and humidity data from the DHT22 sensor (JSON values value:"temperature" and value:"humidity") are automatically mapped to "sensor_temperature" and "sensor_humidity" and are not displayed on the map or website of the sensor.
When mapping to temperature and humidity manually, the data is displayed correctly on the map, but a second line is created on the graphs. Maybe it is better that data mapping overwrites previous values?
Similarly, DHT22 data ("Temp" and "Humidity" in imported CSV) imported from madavi.de are assigned to sensor_temperature and sensor_humidity.

**Comment by trekawek** [comment]
The aqi.eco was created with the [Nettigo Air Monitor](https://nettigo.pl/products/nettigo-air-monitor-kit-0-3-2-zbuduj-wlasny-czujnik-smogowy) in mind, which uses the DHT22 as the heater sensor. That's the most common use-case.

Perphaps we can add a dropdown when adding a new device, to choose the type of sensor (eg. Luftdaten, Luftdaten with heater aka NAM or Smogomierz) to pre-define appropriate mappings.

As for the two lines on the graph, could you send a link presenting the issue?

**Comment by skornpion** [comment]
You can see the issue in the charts from this sensor: https://hornowek.aqi.eco/banacha/banacha01/graphs.
Mapping the "temperature" from JSON to the "temperature" in the sensor results in two identical values in the reading (although there are differences in the chart, I don't know what they result from if one reading is copied to another).

**Comment by trekawek** [comment]
Thanks, this should be fixed with b3f0da084357ec7670e1e9c0add1b266c8019032.
