### ISSUE TITLE
Zaokrąglenie wartości aproksymowanych na wykresie

### ISSUE THREAD

**Issue by prezeskk** [trekawek/air-quality-info#28]
W momencie gdy z czujnika nie są przesyłane dane (rozłączenie z sieci itp) na wykresie jest aproksymowana wartość. Po najechaniu kursorem na takie miejsce pokazują się wartości które nie są zaokrąglone do 2 miejsc po przecinku. Czy jest możliwość poprawy tego?

![Zrzut ekranu 2020-02-16 13 42 33](https://user-images.githubusercontent.com/1465859/75419089-56a4c880-5935-11ea-9e58-d5a803cbbdcf.png)

**Comment by trekawek** [comment]
Da się zrobić. Podeślesz linka? Nie mogę akurat znaleźć czujnika z tymi dziurami.

**Comment by prezeskk** [comment]
Jasne. Id czujnika 6518554
https://air.cmza.ovh/pl

**Comment by trekawek** [comment]
Poprawione.

**Comment by prezeskk** [comment]
Super
