### ISSUE TITLE
Password reset for account

### ISSUE THREAD

**Issue by pawel-zoltak** [trekawek/air-quality-info#43]
Hi guys,
please add password reset for account. I forgot my password and dont't know what to do...
I think its not only my problem.
thx

**Comment by kolobock** [comment]
I am experiencing the same issue. Could not manage my sensor because of lost password...

**Comment by trekawek** [comment]
It's now possible to reset the password:
https://aqi.eco/forgetPassword

Commit:
61d58da0081b4a09270dbc3bf13503b28a20775d
