### ISSUE TITLE
Full graph activation for a Sensirion SPS-30 sensor.

### ISSUE THREAD

**Issue by icnmfabro** [trekawek/air-quality-info#44]
It would be nice to enable all full graphics management for a Sensirion SPS-30 sensor.
The data in question are:

* PM1
* PM4

Particle matter counts:

* NC0.5 
* NC1.0
* NC2.5
* NC4.0
* NC10.0
* TS

**Comment by trekawek** [comment]
Hi @icnmfabro,

I think it's all already supported, eg.:
https://nettigo.aqi.eco/pl/sensor-2

For the NC, they are prefixed with `#`:
https://nettigo.aqi.eco/pl/sensor-2/graphs

For the full list of supported measurements, please check:
https://github.com/trekawek/air-quality-info/blob/20a7812005cf8523e79e34a3f45d5eba7f8ad00d/src/htdocs/model/updater.php#L7-L23
