### ISSUE TITLE
Błędy 

### ISSUE THREAD

**Issue by romeok01** [trekawek/air-quality-info#5]
Mam takie błędy i nie idzie zainstalować

root@pi:/home/pi# bash -e /tmp/install.sh
Installing packages...
W: Nie udało się pobrać http://repo.mutability.co.uk/raspbian/dists/wheezy/InRelease

W: Nie udało się pobrać http://repo.mutability.co.uk/raspbian/dists/wheezy/Release.gpg  Nie udało się przetłumaczyć nazwy "repo.mutability.co.uk"

W: Nie udało się pobrać niektórych plików indeksu, zostały one zignorowane lub użyto ich starszej wersji.
E: Błąd, pkgProblemResolver::Resolve zwrócił błąd, może to być spowodowane zatrzymanymi pakietami.
root@pi:/home/pi#

**Comment by romeok01** [comment]
Błąd pojawia się przy instalacji tego:
pi@pi:~ $ sudo apt-get install -qq nginx php-fpm php-rrd curl zip net-tools > /dev/null
E: Błąd, pkgProblemResolver::Resolve zwrócił błąd, może to być spowodowane zatrzymanymi pakietami.

**Comment by trekawek** [comment]
@romeok01  - do działania wymagana jest najnowsza wersja Raspbiana - 9 Stretch. Do ściągnięcia tutaj:

https://www.raspberrypi.org/downloads/raspbian/

"Raspbian Stretch Lite" powinien być OK.

**Comment by romeok01** [comment]
Zainstalowałem najnowszy Raspbian i zainstalowało się poprawnie.
