### ISSUE TITLE
Invalid locations urls in the site menu on the /about page

### ISSUE THREAD

**Issue by wotnak** [trekawek/air-quality-info#51]
When on the `/about` page all locations are linked to the current page instead of the locations pages.

**How it currently works on the `/about` page**:
- when you open the `/about` page (for example https://mosina.aqi.eco/en/about),
- and select specific location in the site menu (for example  `Locations` >  `Ul. Juliana Tuwima`),
- you are redirected back to the `/about` page (for example https://mosina.aqi.eco/en/about).

**How it works on all other pages**:
- when you open any other page (for example https://mosina.aqi.eco/en/),
- and select specific location in the site menu (for example `Locations` >  `Ul. Juliana Tuwima`),
- you are redirected to the selected location page (for example https://mosina.aqi.eco/en/tuwima).

**Comment by trekawek** [comment]
I fixed it in 4f75d3a, thanks!
