### ISSUE TITLE
Invisible text on sensor map popups when the dark theme is selected

### ISSUE THREAD

**Issue by wotnak** [trekawek/air-quality-info#52]
When the dark theme is selected some text on sensor popups on the map is invisible (white text on white background).

For example: 
with dark theme (https://eko.edial.pl/pl/map?theme=darkly)
![image](https://user-images.githubusercontent.com/52507690/110318500-da47c980-800d-11eb-8a20-ba2cd4b02fd6.png)
with default light theme (https://eko.edial.pl/pl/map?theme=default)
![image](https://user-images.githubusercontent.com/52507690/110318689-1713c080-800e-11eb-853e-99a8f2ce4bc3.png)

I think the best solution would be to make popup background dark when the dark theme is selected. This would not only fix the text visibility issue but also popups would better match the colors of the rest of the site.

A nice improvement would be also automatically switching the map to night view when the dark theme is selected.

**Comment by trekawek** [comment]
I implemented the auto-switch to night view in darkly theme and added a dark background to the InfoWindow. There are ugly white borders, but I'm not sure they can be removed with CSS. PRs with fixes ale welcome :)

**Comment by trekawek** [comment]
Eventually I decided to keep the white background and use dark text. Thanks for the report!
