### ISSUE TITLE
The response to sudden changes on the home page is slow (on the widget and the graph)

### ISSUE THREAD

**Issue by dblachut** [trekawek/air-quality-info#55]
I am talking about a situation where the air quality was fine for the past hour, but it suddenly starts to be poor.
For such and opposite cases the reaction on the website is delayed because (if I am not mistaken) it displays the average value over the last hour.

I would like to use the aqi.eco for checking the current air quality, for me it makes more sense to display the latest results on the widget and more detailed results on the graph by default. Other applications such as Kanarek responds to instant changes much better (probably only latest result is taken into account).

My proposal is to e.g.:
- add an option to the widget to display the result based on the latest (or N last) measurement(s)
- add something like "Instantaneous"/"15min" mode to the chart on the main page

The issue is somewhat related to #14, but I guess this option lives under "Instantaneous" feature in "Graphs"?

**Comment by dblachut** [comment]
I could maybe help, but the fact that the site is written in PHP pushes me away a bit. ;)

But if there will be no desire for such change for now I would appreciate some introduction - where the changes should be applied and I hope I will manage to do it by my own.

**Comment by dblachut** [comment]
I think I have found the code that is responsible or this and it probably shouldn't be that hard (probably passing some option to widget which is in an `iframe` is the worst part). Although I think it would be the best to leave it to the author.

IMHO the best option would be to:
1. add "latest" option in `Average` before `(1h / 24h)` as `(latest / 1h / 24h)`
2. make this option the default one; if not save this option in e.g. some cookie to remember users choice
   - this option could have effect on the widget, table and optionally the graph ("Instantaneous" mode)

Please let me know if you agree and if that is feasible.

**Comment by trekawek** [comment]
@dblachut - yes, the displayed values are the averages, an hourly or daily one.

I don't want to change this behaviour. The averages are more resistant to random events, eg. old car driving under the window. What's important, the air quality indexes are also defined for the averages:
https://www.airqualitynow.eu/about_indices_definition.php

aqi.eco tries to implement this index, and depending on the average type: 1h or 24h, it uses different thresholds. There's no index for the "latest" measurements.

That being said, I think it wouldn't hurt to have the "latest" as an option for the averages on the main page. Maybe we can use 1h indexe thresholds for this. It can't be default for the reasons above, but as a separate issue we may introduce the cookie mechanism you've mentioned.

**Comment by dblachut** [comment]
Okay, that is understandable. On the other hand the most basic use case of having air quality monitor is to know whether it is healthy or not to go outside for a walk **currently**. This is probably also the reason why e.g. Kanarek displays latest measurement.

I think is is pretty common case that the air quality drops suddenly in our country - e.g. after the sunset/temperature drop and stays this way approximately until the sunrise. Last but not least - is is up to the owner to put the monitor in the place where it will not be affected by random events. What if the car drives under the window more than once during past hour? The results from such a device are not reliable anyway.

But as I said - I understand your approach and of course I don't insist on changing the default behavior. :)

I think there is already some user preference saving method for the theme that is used?
Will you be able to implement this feature?

**Comment by dblachut** [comment]
One more thing came to my mind - if the latest result is random or the user suspect that it might be random (for whatever reason) - the page can be refreshed shortly to get another one. Typically the devices report the pollution every few minutes.

**Comment by dblachut** [comment]
I am already on it. (I am writing so we don't duplicate our work)
