### ISSUE TITLE
1h average graphs with Instantaneous mode.

### ISSUE THREAD

**Issue by trekawek** [trekawek/air-quality-info#63]
It seems that after refershing, the cookie selects the recently used mode, but the graph uses default anyway.

Steps to reproduce:
1. Open https://mosina.aqi.eco/en/puszczykowo/bajkowewzgorze/graphs
2. Click "Instantaneous"
3. Refresh page.

Result:
- the graph displays 1h averages, even though the instantaneous label is selected

Expected:
- the graph displays instantaneous *or* label is set to 1h

**Comment by trekawek** [comment]
@dblachut - is this something you can take care of? Thanks!

**Comment by dblachut** [comment]
#64 :-)
