### ISSUE TITLE
Data not received at aqi.eco 

### ISSUE THREAD

**Issue by aaaprahamian** [trekawek/air-quality-info#69]
Hi, I have a sensor ID 2476676. Since 28th it stopped collecting and transmitting data. Firmware version: NRZ-2020-133/EN (Nov 29 2020). Can you please advise how can I troubleshoot the sensor and understand what the issue is and how to fix it? I have not changed anything and the stop is sudden.
https://maps.sensor.community/#16/42.6554/23.2595

![Screenshot_20210629-200810](https://user-images.githubusercontent.com/86680574/123905176-7e1d0280-d97a-11eb-9ff7-3e8de3311276.png)

**Comment by trekawek** [comment]
Hi @aaaprahamian,
I think you should check the "https" box if you're using port 443. Please let me know if it helps.

Also, it may be a good idea to regenerate the token in the aqi.eco admin console (the one visible in api.aqi.eco/...) and then update it in the device - it's supposed to be secret.

**Comment by aaaprahamian** [comment]
Hi @trekawek I tried this but it didn't work. I tried now to link the aqi.eco profile by using the sensor community option and link it to the map of the sensor community and it started working again. Now instead of getting the data directly from the sensor it takes the data from the web but it is ok for me. 

Thanks for the help!

Api
