### ISSUE TITLE
Feature request: location: with radius, randomize location on map within radius

### ISSUE THREAD

**Issue by ProBackup-nl** [trekawek/air-quality-info#81]
For privacy purposes I wouldn't like to disclose the exact sensor location.

I enabled a 250 meter radius. That draws a circle around the location on the (Google) map. But the center is always located on exactly the point.

I'd wish the center of the radius drawn on the map to be randomized. The exact location should not be visible in any source code (json, html, js, or whatever).

**Comment by jckkk** [comment]
Randomization would actually reveal the location, as taking a few readings and averaging would reveal the point. The current solution is better, as you can just pick the centre of the circle yourself and it doesn't have to be the exact location of the sensor.

**Comment by trekawek** [comment]
Thanks @jckkk and @ProBackup-nl, this is actually the approach I took as well with my sensors.
