### ISSUE TITLE
/map view misses "Graphs" menu entry

### ISSUE THREAD

**Issue by ProBackup-nl** [trekawek/air-quality-info#84]
environment:
Locations = 2

1. /device/2520, 
- direct sensor (location not enabled)
2. /sensor/2525,
- linked to sensor.community (location enabled, sensor-id = empty)

Home view menu bar:
![Air quality - Home view - menu bar](https://user-images.githubusercontent.com/515451/146354120-2444fece-8da9-4735-84f5-284b13ce8f21.png)

Map view menu bar:
![Air quality – Map view - menu bar](https://user-images.githubusercontent.com/515451/146354334-859bcf9d-a40d-45bd-bd7e-d435f98c4f71.png)

**Comment by trekawek** [comment]
The /graphs always present results for a particular device. If there's no device selected (eg. the /map where all of them are visible), the /graphs is hidden.
