### ISSUE TITLE
Reversed date and day format for NL locale

### ISSUE THREAD

**Issue by ProBackup-nl** [trekawek/air-quality-info#85]
After https://github.com/trekawek/air-quality-info/commit/6d5e275566afcb27d4f524fedf19cfd2b92f5be2 there should be dutch locale support for graph datetime formatting. I see dutch locale appearing in [vendor.min.js](https://github.com/trekawek/air-quality-info/blob/master/src/htdocs/public/js/vendor.min.js) in the client browser.

Despite this, the dates are still displayed "MMM. D" (dec. 16) where in dutch locale the format should be reversed "D MMM." (16 dec.).

Wish: include the day name of the week (en:thu 16 dec.; nl:don 16 dec.) or even shorter (en:th 16 dec.; nl:do 16 dec.) in the xAxis label and tooltip.

**Comment by trekawek** [comment]
Fixed in cda083a.

**Comment by ProBackup-nl** [comment]
Thanks again, for the quick improvement.
