### ISSUE TITLE
Feature request: no hyperlink on brand icon

### ISSUE THREAD

**Issue by ProBackup-nl** [trekawek/air-quality-info#86]
Users click there and get let because they end up on a different (sub)domain: aqi.eco instead of subdomain.aqi.eco.

Workaround is to hide the logo completely with this template css style:
`nav>a.navbar-left.navbar-brand.aqieco{visibility:hidden;}`

Disabling/removing the hyperlink only, is not an option in css.

**Comment by trekawek** [comment]
That's done in 26db006.
